apiVersion: v2
description: Installs pihole in kubernetes
name: pihole
appVersion: "2025.11.1"
version: 1.0.0
dependencies:
  - name: pihole
    version: 2.35.0
    repository: https://mojo2600.github.io/pihole-kubernetes/