pihole:
  # DNS Service Configuration
  serviceDns:
    type: LoadBalancer
    loadBalancerIP: "192.168.177.240"
    annotations:
      metallb.universe.tf/allow-shared-ip: "pihole-svc"
  
  # DHCP Service Configuration
  serviceDhcp:
    enabled: false
  
  # Web Interface Configuration
  serviceWeb:
    type: LoadBalancer
    loadBalancerIP: "192.168.177.240"
    annotations:
      metallb.universe.tf/allow-shared-ip: "pihole-svc"
  
  # Environment variables to allow web access
  extraEnvVars:
    VIRTUAL_HOST: "192.168.177.240"
    CORS_HOSTS: "192.168.177.240"