pihole:
  # DNS Service Configuration
  serviceDns:
    type: LoadBalancer
    loadBalancerIP: "192.168.1.240"
    annotations:
      metallb.universe.tf/allow-shared-ip: "pihole-svc"
  
  # DHCP Service Configuration
  serviceDhcp:
    enabled: false
  
  # Web Interface Configuration
  serviceWeb:
    type: LoadBalancer
    loadBalancerIP: "192.168.1.240"
    annotations:
      metallb.universe.tf/allow-shared-ip: "pihole-svc"