pihole:
  # Use dnsHostPort to bind DNS to node IP on port 53
  dnsHostPort:
    enabled: true
    port: 53
  
  # DNS Service Configuration
  serviceDns:
    type: ClusterIP
  
  # DHCP Service Configuration
  serviceDhcp:
    enabled: false
  
  # Web Interface Configuration
  serviceWeb:
    type: NodePort
  
  # Environment variables
  extraEnvVars:
    FTLCONF_dns_listeningMode: "all"