apiVersion: v2
description: Installs metallb in kubernetes
name: metallb
appVersion: "2025.11.1"
version: 1.0.0
dependencies:
  - name: metallb
    version: 0.14.8
    repository: https://metallb.github.io/metallb