onepassword-connect:
  # Use the pre-created secret containing 1password-credentials.json
  connect:
    credentials_base64: ""
    credentialsKey: "1password-credentials.json"
    credentialsName: "onepassword-credentials"